# Generated by Django 4.2.20 on 2025-04-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
